name: Routes Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Test routes
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.23.3'  # Adjust to your Go version

    - name: Install dependencies
      run: |
        go mod tidy
        go mod vendor

    - name: Run backend
      run: |
        go run .

    - name: Wait for server to start and check if routes are reachable
      run: |
        retries=10
        while [ $retries -gt 0 ]; do
          if curl --fail http://localhost:8080/; then
            echo "Server is up!"
            break
          fi
          echo "Server not up yet, retrying..."
          retries=$((retries - 1))
          sleep 2  # Wait for 2 seconds before retrying
        done

        # If we ran out of retries, fail the step
        if [ $retries -eq 0 ]; then
          echo "Server failed to start"
          exit 1
        fi

    - name: Check if routes are reachable
      run: |
        curl --fail http://localhost:8080/ || exit 1
        curl --fail http://localhost:8080/login || exit 1
        curl --fail http://localhost:8080/register || exit 1
